### ISSUE TITLE
compose: Give better media-picker UI on Android

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#114]
See https://github.com/zulip/zulip-flutter/issues/56#issuecomment-1514001281 (referring to what we currently offer on the "Attach images or videos" button in the compose box):

> > Hmm no, I don't think this is the fancy new `PhotoPicker` API
> 
> Dang, yeah.
> 
> That PhotoPicker API is available through image_picker: https://pub.dev/packages/image_picker_android#photo-picker
> 
> So that'd be an option. But pending [flutter/flutter#89159](https://github.com/flutter/flutter/issues/89159), it'd lack videos unless we had two separate buttons.

That issue now has a linked PR! 🤞 https://github.com/flutter/packages/pull/3892 So hopefully we can take care of this reasonably soon, by using `image_picker` instead of `file_picker` for this.

**Comment by gnprice** [comment]
And that upstream issue https://github.com/flutter/flutter/issues/89159 is complete (since a few weeks ago). So the first-party `image_picker` should be able to take care of this for us.

Also the first-party `file_selector` just grew Android support:
* https://github.com/flutter/flutter/issues/110098

We'd noted in #57 that that was missing, which led us to use `file_picker` there. But now we may be able to replace both uses of `file_picker` with first-party plugins.

This means there's overlap in functionality between the two first-party plugins `file_selector` and `image_picker`:
* https://github.com/flutter/flutter/issues/128960

Not sure which to use where they overlap. Quite possibly either one would be fine.

**Comment by gnprice** [comment]
This appears to have been fixed — I just tried the "photo" icon under the compose box, on Android, and got what looks like the fancy new "photo picker" UI.

**Comment by gnprice** [comment]
Closing because the issue seems to have been fixed.

I am puzzled as to what would have fixed it, though:
* The code sure looks like we're still using `package:file_picker` for that button.
* There's nothing in that package's changelog that looks relevant: https://pub.dev/packages/file_picker/changelog
* I only find one related issue in that package's issue tracker… and it's an open issue asking for precisely this feature, filed just a week ago: https://github.com/miguelpruivo/flutter_file_picker/issues/1559
