### ISSUE TITLE
autocomplete: Add user avatars to user-mention autocompletes

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#227]

**Comment by sm-sayedi** [comment]
I would like to work on this issue!

So far, my work looks like this:

<img src="https://github.com/zulip/zulip-flutter/assets/59946442/b89191b9-471e-4ebf-8dc5-784f2176b52d" width="300"/>

**Comment by gnprice** [comment]
@sm-sayedi Thanks! Please go ahead.

That demo looks good, except that I'd put less vertical spacing between the items in the results. If you can find an example of this UI in @terpimost's [Figma design for mobile](https://www.figma.com/file/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=0-1), though, then follow what that says. @terpimost might also add a comment in this thread.

(As usual, please prioritize revisions on existing PRs over starting new ones — so that means revising #560 based on the feedback in the review I just left there. But once that's all ready for another review, this would be a good next issue.)
