### ISSUE TITLE
autocomplete: Sort user-mention autocomplete results

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#228]
Perhaps by name, to start with, but really:

https://github.com/zulip/zulip-flutter/pull/207#pullrequestreview-1520406847

> (Or better yet something more relevant than name: some kind of relevance to search plus relevance to the context, like people subscribed to the stream or that have talked recently in the narrow. But sorting by user ID seems like it's just going to feel weird and arbitrary to people.)

**Comment by sm-sayedi** [comment]
I would like to work on this one!

So far I've made it sorted by the name.

<table>
    <tr>
        <td><b>Before</b></td>
        <td><b>After</b></td>
    </tr>
    <tr>
        <td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/476ab511-654f-4458-8297-589a4f6ae43d" width="300"/></td>
        <td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/538672fd-8c90-4663-a742-6e492d2a429c" width="300"/></td>
    </tr>
</table>

**Comment by gnprice** [comment]
@sm-sayedi Sure, please do — assigning to you.

I think a good behavior to shoot for here would be to sort it the same way Zulip web does. There might be things that can be improved there, but if so then they should probably be changed there too. Two particular things I believe it uses that would be helpful:
* people who've recently participated in the conversation you're looking at get shown sooner
* people who you've had DM conversations with get shown sooner

In general we keep less message history in the mobile client than the web client, because of the different context, so that might affect what information we have for implementing some of the same features.

But if there are other kinds of data that would help implement the same features as web, and that we don't currently track in the store but are part of the [/api/register-queue](https://zulip.com/api/register-queue) response, then we can take this as a prompt to add those to our API bindings and start tracking them in the store, as part of implementing this issue.

And as usual, if anything seems uncertain or you have any questions as you're going about that, please ask in `#mobile-team` and we'll be glad to discuss.

**Comment by chrisbobbe** [comment]
@sm-sayedi with #828 merged, what remains to be done here? 🙂

**Comment by sm-sayedi** [comment]
As mentioned in #608 description:
> 3. Human vs. Bot users.
> 4. Alphabetical order.

So one other PR is needed to close this issue. 😃

**Comment by gnprice** [comment]
Great!

Both of those sound like they'll be easier than the two we've already done — in particular they don't involve maintaining any new data structures. So looking forward to seeing those last two facets of this feature completed soon. :slightly_smiling_face:
