### ISSUE TITLE
ui: Stream colors

### ISSUE THREAD

**Issue by sirpengi** [zulip/zulip-flutter#368]
Display stream colors where appropriate.

- api reference
  - See `color` in https://zulip.com/api/get-subscriptions#response
- zulip-mobile
  - `getStreamColorForNarrow` in https://github.com/zulip/zulip-mobile/blob/main/src/subscriptions/subscriptionSelectors.js
  - `getStatusBarColor` in https://github.com/zulip/zulip-mobile/blob/main/src/common/ZulipStatusBar.js
- web
  - `get_recipient_bar_color` in https://github.com/zulip/zulip/blob/main/web/src/stream_color.ts

**Comment by gnprice** [comment]
Stream colors were implemented in the API binding in 9c1128eb9555dd8bfe053275cc30b63a88ef9eee and shown in recipient headers since 63760a90ebd057a7ffac2889ad612b69f9b2c240, in the first few days of the prototype.

The complex ways that the colors are mixed and lightened for different contexts were implemented more recently, in `StreamColorSwatch`, as part of work on the inbox screen.
