### ISSUE TITLE
Fix alignment of server version on home screen

### ISSUE THREAD

**Issue by alya** [zulip/zulip-flutter#428]
There is a horizontal alignment issue with the server version on the home screen. We should center it like all the other items on the page, and make sure that there is a reasonable margin around it.

**Comment by gnprice** [comment]
As a debugging clue: I think this issue appears specifically when the version line is longer than the width of the screen, and therefore wraps. (Which is typical if you're on chat.zulip.org or Zulip Cloud, rather than a numbered release, and if you have a phone with default display settings.) When it fits as a single line, it gets centered as intended.
