### ISSUE TITLE
Issue: Account Button Asking for Server URL in Zulip Flutter Application

### ISSUE THREAD

**Issue by DeepeshKalura** [zulip/zulip-flutter#448]
### Steps to Reproduce:

1. Clone the Zulip Flutter repository to your local machine.
2. Run the application.
3. Observe that the account button is prompting for a server URL.

Additional Information:

0.0.7 Version of Zulip Flutter being used.

Any relevant error messages or console output.
Screenshots illustrating the issue:
<table>
<tr>
<td>  <img src= "https://github.com/zulip/zulip-flutter/assets/99230888/ac3e85fb-3b12-407d-8bee-2a78a16649b2" width= 150>
<td>  <img src = "https://github.com/zulip/zulip-flutter/assets/99230888/375e2db2-56c4-4150-a2d0-a812a816c518" width=150>
<td>  <img src = "https://github.com/zulip/zulip-flutter/assets/99230888/72664ef7-8be2-4274-8707-acc3f01c198d" width =150>
</tr>
</table>

Request for Assistance:
As a newcomer to open-source contributions, I am unsure about the type of account needed in this context. Clear documentation or guidance on the account type required for development would be beneficial.

**Comment by chrisbobbe** [comment]
Do you have an account in any Zulip organization? If not, I recommend reading [this page of documentation](https://zulip.com/development-community/) and joining the Zulip development community.

Then this doc can help you find the server URL: https://zulip.com/help/logging-in . But I'll go ahead and tell you that `https://chat.zulip.org` is the URL for the Zulip development community.

Before publishing the app to a wide audience, we should make it clear what a "server URL" is and how to find yours. That's this issue:

- https://github.com/zulip/zulip-flutter/issues/109

Since we already have an issue tracking that, I'll go ahead and close this issue.
