### ISSUE TITLE
Creating a Demo Account for Testing

### ISSUE THREAD

**Issue by neeldoshii** [zulip/zulip-flutter#454]
I think we can have a development server or any demo server for testing.

In my case I used the zulip server for testing `https://chat.zulip.org/`

So what my idea is that we can have a static field like

Server : `https://chat.zulip.org/`
Email : 'test@zulip.com'
Password : 'zulip123'

This email and pass will only work in debug mode but not in release mode. 

What do you think about it?

**Comment by gnprice** [comment]
We won't be creating a central shared demo account. That makes it too easy for one person's usage to interfere, by accident or otherwise, with another person's.

For most purposes, it works well to just use your own main account on chat.zulip.org. Test messages go in the `#test here` stream, just like they would if sent from a test/demo user.

When needed, you can create your own test account on chat.zulip.org. You can also create a test organization in Zulip Cloud, or use your own [Zulip development server](https://zulip.readthedocs.io/en/latest/development/overview.html). Connecting the mobile app to a Zulip dev server requires [a couple of extra steps](https://github.com/zulip/zulip-mobile/blob/main/docs/howto/dev-server.md); that documentation was written for zulip-mobile but applies exactly the same to zulip-flutter.
