### ISSUE TITLE
In user-agent, include platform, platform version, and app version

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#467]
In the first pass for

- #406

, Greg [suggests](https://github.com/zulip/zulip-flutter/pull/450#discussion_r1433366608) leaving out the platform, platform version, and app version. So I expect the user agent will look something like 

```
ZulipMobile (actually ZulipFlutter)
```

instead of e.g.

```
ZulipMobile (Android 14) (actually ZulipFlutter/1.2.3)
```

. This issue is for filling in those missing things.

**Comment by gnprice** [comment]
In particular, after #471 there will be (as discussed at https://github.com/zulip/zulip-flutter/pull/471#issuecomment-1874756255) a sort of residual version of the following issue:
* #460

which is that the login emails will say "Device: Zulip on an unknown operating system" rather than the actual operating system.

Fixing this issue should fix that. When we have a PR for this issue, one thing we should manually test in it is that it does indeed fix that.
