### ISSUE TITLE
content: **bold text** should be formatted with `weightVariableTextStyle`

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#499]
Like other text that we want to present in Source Sans 3 (a variable-weight font), we should style `**bold text**` in content with `weightVariableTextStyle`. Currently, it is styled with just `fontWeight`:

```dart
  InlineSpan _buildStrong(StrongNode node) => _buildNodes(node.nodes,
    style: const TextStyle(fontWeight: FontWeight.w600));
```

**Comment by gnprice** [comment]
Writing down a discussion we had in the office: it looks like the symptoms of this bug are currently subtle, but only because of the upstream Flutter issue discussed at #500.

The TextStyle that ultimately applies to the text inside one of these spans inherits a `fontVariations` from an ancestor, which in a paragraph is going to be the one `weightVariableTextStyle` gives for normal weight. In the absence of that upstream issue, the `wght` variation from there would control (probably, depending on how the issue gets resolved), and the text would have normal weight (on default system settings) despite being from a `StrongNode`.

But with that issue, the `fontWeight` combines with the `wght` variation and we get a bold effective weight. Effectively this bug roughly cancels out with #500 (… at least on Android, where #500 applies). I say "roughly" because even in the scenario where they both trigger, the effect of #500 seems to make the glyphs heavier but leave their spacing unchanged, so it's not quite the same effect as getting the actual bolder version of the font.
