### ISSUE TITLE
choose-account: Scroll viewport awkwardly starts 8px below app bar

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#606]
| Current | Would be better |
| --- | --- |
| ![76E88B36-C44D-4737-AAB7-F0F2C84FBBB0](https://github.com/zulip/zulip-flutter/assets/22248748/c153ca4f-adf4-4261-9662-4a56b1e6ce4d) | ![A90C589F-09E5-48B8-9B5A-A86757D5EA17](https://github.com/zulip/zulip-flutter/assets/22248748/eddee67a-353f-4312-bea3-5702968f21c2) |

**Comment by chintu4** [comment]
Can you describe the issue properly

**Comment by gnprice** [comment]
@chintu4 The issue is described in the title of the issue thread, and illustrated in the screenshots above. If you look closely at what's different between the screenshots, focusing on just below the app bar (as pointed to by the title), you should see it.

Chris also sent a PR fixing the issue, which is linked here. So if you look at the code of that PR, that may help make it clearer for you.
