### ISSUE TITLE
Overlapping Modals in Share Functionality

### ISSUE THREAD

**Issue by Syrineladeb02** [zulip/zulip-flutter#655]
When attempting to share a message in the Zulip Flutter app by right-clicking, users encounter an issue where two modal dialogs appear simultaneously. Initially, a small message indicating "sharing failed" pops up, followed by another modal prompting users to share with specific individuals. However, the "sharing failed" message remains visible underneath the second modal, causing confusion and cluttering the interface.

https://github.com/zulip/zulip-flutter/assets/152219936/cec814af-e5bc-4937-8db2-1b68b53c4bdf

**Comment by chrisbobbe** [comment]
Thanks for the screen recording! Is this an issue you've also seen when you run the app on Android or iOS, or just on your computer like that?

**Comment by Syrineladeb02** [comment]
Yes, I've been testing the Zulip Flutter app exclusively on my computer, and I encountered this issue during my usage. I haven't tested it on mobile devices like Android or iOS yet.

**Comment by gnprice** [comment]
Thanks for the report. I'm closing this because our desktop support is for development only, and doesn't include platform integrations (like "share a message").

It looks like we hadn't previously written this down anywhere in the tree, so I've just now gone and [added it](https://github.com/zulip/zulip-flutter/commit/423600dd3cf63edc27ccd7f8d4bc29ed49a5e977?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) — please take a look at the new ["Desktop support" section](https://github.com/zulip/zulip-flutter?tab=readme-ov-file#desktop-support) at the end of the README, and let us know if anything's unclear after reading that.

(The one place we'd previously discussed this was in [a chat message a while ago](https://chat.zulip.org/#narrow/stream/2-general/topic/Flutter/near/1492614) when the Flutter app was a new prototype. Naturally that's not a place we expect contributors to have read.)
