### ISSUE TITLE
Please help! UI

### ISSUE THREAD

**Issue by Danilz-2706** [zulip/zulip-flutter#812]
I can't find a way to solve this function like messenger app or telegram app. Overriding the message will display such UI

https://github.com/user-attachments/assets/da3cad50-1f08-45f6-bf67-09f5004c8d4c

**Comment by gnprice** [comment]
Hello. Can you say more about what you're trying to do?

In the Zulip mobile app, if you long-press on a message, you'll get a set of options similar to the ones in your screen recording above.

**Comment by Danilz-2706** [comment]
Thank you. I want to 

> Hello. Can you say more about what you're trying to do?
> 
> In the Zulip mobile app, if you long-press on a message, you'll get a set of options similar to the ones in your screen recording above.

I'm trying to create an effect when pressing on a message similar to the one above. I'm looking for keywords to make it.

**Comment by gnprice** [comment]
I see. If I understand correctly, this isn't a question about Zulip, then, right? You're looking to create a certain effect in a different app you're writing, and are looking for help.

This isn't really the venue for such a question, but you're in luck because we have talked about such a thing for this app: so you might find the discussion and links in #62 helpful. In particular Apple calls that a "context menu":
https://developer.apple.com/design/human-interface-guidelines/context-menus
and if you're using Flutter, there's a widget for it called CupertinoContextMenu:
https://api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html

Best of luck with your app.
